apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-stress-simulator-spot
spec:
  selector:
    matchLabels:
      app: web-stress-simulator-spot
  template:
    metadata:
      labels:
        app: web-stress-simulator-spot
        workload: web-stress-simulator
    spec:
      containers:
      - name: web-stress-simulator-spot
        image: flaviostutz/web-stress-simulator
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /web-stress-simulator-1.0.0/cpu?time=100
            port: 8080
        resources:
          requests:
            cpu: 500m
          limits:
            cpu: 500m
      nodeSelector:
        kubernetes.azure.com/scalesetpriority: spot
      tolerations:
      - key: "kubernetes.azure.com/scalesetpriority"
        operator: "Equal"
        value: "spot"
        effect: "NoSchedule"
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: web-stress-simulator-spot
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web-stress-simulator-spot
  minReplicas: 1
  maxReplicas: 50
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 30
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 200
        periodSeconds: 5